### ISSUE TITLE
Issue with Vue.js and Brunch 2.3

### ISSUE THREAD

**Issue by Diamond** [brunch/brunch#1179]
A few people have reported an issue and I was able to reproduce this myself. When using Brunch 2.3 with Vue.js, the application builds just fine but you'll get errors when you load the page up in a browser with "Uncaught TypeError: Cannot read property 'NODE_ENV' of undefined"

Here is the full stacktrace:

`Uncaught TypeError: Cannot read property 'NODE_ENV' of undefined
(anonymous function) @ vue.common.js:984
(anonymous function) @ vue.common.js:9596
initModule @ app.js:63
require @ app.js:73
expanded @ app.js:56
(anonymous function) @ vue.common.js:9597
initModule @ app.js:63
require @ app.js:73
(anonymous function) @ socket.js:62`

The line from vue.common.js it is complaining about is:

`if (process.env.NODE_ENV !== 'production') {`

I've created a repo showcasing this problem at https://github.com/Diamond/brunch-2.3-vuejs-error (it requires Elixir/Phoenix to run).

This issue does not occur with Brunch 2.1.x or 2.2.x, only 2.3.x. Let me know if you need any more details and I'll be happy to provide whatever I can. I'm still researching if this is the cause of some other issues with React.js that have been reported to me.

**Comment by Diamond** [comment]
Okay, I tested out React.js as well and it runs into the same issue. Here is the repo that introduces the issue (again, requires Elixir and Phoenix to run):

https://github.com/Diamond/brunch-2.3-reactjs-error

Here is the line it fails on (same error message as the above):
` if (process.env.NODE_ENV !== 'production') {`

**Comment by goshakkk** [comment]
@Diamond this was already addressed in master. It's not part of any release — yet, but can you check with the version from GH master? (`npm install -g brunch/brunch` / ``npm install -brunch/brunch`)

relevant commit: https://github.com/brunch/brunch/commit/225291dca5b61b1e5efd5c47dd65d417dc6ec4a9

**Comment by Diamond** [comment]
Unfortunately that introduces a new error:

`$ brunch b
17 Feb 09:50:05 - error: undefined of web/static/js/socket.js failed. or: xBrowserResolve is not a function ; undefined of web/static/js/app.js failed. or: xBrowserResolve is not a function`

**Comment by enna** [comment]
I've got the same issue with a Reactjs project.

At first I got `Uncaught TypeError: Cannot read property 'NODE_ENV' of undefined` in my browser, and then I just couldn't build my client side scripts with brunch because of `xBrowserResolve is not a function` errors.

I worked with Brunch 2.3.1, so I came back to 2.2.3 and everything is fine again.

**Comment by paulmillr** [comment]
Fixed in 2.3.2. Sorry folks

**Comment by enna** [comment]
That works fine with 2.3.2. :)
Thanks!!

**Comment by Diamond** [comment]
Verified that 2.3.2 fixes all of the issues I was having! I'll update my blog posts to note this! Thanks for the fast response! :100:
