### ISSUE TITLE
Error with react-addons-pure-render-mixin

### ISSUE THREAD

**Issue by chrismcg** [brunch/brunch#1209]
### Description

Upgrading a project from 2.1.2 to 2.4.2 and something is going wrong with `import PureRenderMixin from 'react-addons-pure-render-mixin';`

The error I'm getting is:

`Uncaught Error: Cannot find module "react/lib/ReactComponentWithPureRenderMixin" from "react-addons-pure-render-mixin"`

This was working in 2.1.2. I've created a minimal repo from the `with-react` template that shows the problem here:

https://github.com/chrismcg/brunch_react_bug

### Environment

1. Brunch: 2.4.2
2. Node: 5.7.0
3. NPM: 3.6.0
4. Operating system: OSX 10.9.5

### `package.json` contents

```
{
  "name": "your-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.0.1",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "prod": "brunch build --production"
  },
  "dependencies": {
    "react": "~0.14.7",
    "react-dom": "~0.14.7",
    "react-addons-pure-render-mixin": "~0.14.7"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "babel-brunch": "~6.0.0",
    "babel-preset-es2015": "~6.3.13",
    "babel-preset-react": "~6.3.13",
    "brunch": "^2.4.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0"
  }
}
```

### brunch config contents

```
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'vendor.js': /^(?!app)/,
        'app.js': /^app/
      }
    },
    stylesheets: {joinTo: 'app.css'}
  },

  plugins: {
    babel: {presets: ['es2015', 'react']}
  }
};
```

**Comment by chrismcg** [comment]
May be related to https://github.com/brunch/brunch/issues/1186

**Comment by paulmillr** [comment]
Replace `brunch` version with `brunch/brunch` & npm install and tell us if that does the trick.

**Comment by chrismcg** [comment]
No joy I'm afraid, same problem in the test app linked in the issue.

**Comment by goshakkk** [comment]
Apparently, this is another regression related to #1184, which purpose was to not raise errors when optional dependencies could not be found. At first, it only used package.json's dependencies and was later extended to also work properly with shims and package.json's browser feel. However, it looks like it still lacks the `peerDependencies` check here, so I'm going to add it

**Comment by goshakkk** [comment]
@chrismcg https://github.com/brunch/brunch/pull/1210 should fix it

One other issue with the app you submitted is `export const App = ...` exports `{App}`, not not makes it the default.

**Comment by chrismcg** [comment]
I can confirm #1210 fixes it, made the same change locally (and fixed the App.jsx) and everything worked. Also checked my real application and that fixes it there too. Thanks!
