### ISSUE TITLE
Paths starting with an underscore are excluded without dependency checking

### ISSUE THREAD

**Issue by savuori** [brunch/brunch#1169]
The original error message which led to this issue: Cannot find module "lodash/_isHostObject" from "lodash/isPlainObject"

This issue was previously [raised on redux](https://github.com/rackt/redux/issues/1371). 

Here's a quite minimal setup to [reproduce the error](https://github.com/savuori/redux_issue_1371) (includes the brunch setup and package.json). 

It is probably caused by [this line of code in Brunch](https://github.com/brunch/brunch/blob/795fc4b6814c1355d64b68155cdd7865d882c60b/lib/application.js#L242).

This is with brunch v2.1.3, nodejs v5.5.0, os x 10.10.2

**Comment by goshakkk** [comment]
The issue is already addressed in the Brunch 2.2.x line. Can you try with the most recent version of Brunch (2.2.3)? Should work. 

I know for a fact because I created https://github.com/brunch/redux-skeleton, worked like a charm with 2.2

**Comment by savuori** [comment]
You're right, both the sample project and the original phoenix project I have work with brunch 2.2.3 so this is no longer an issue.
